# Generated by Django 6.0.6 on 2026-09-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_communitypost_post_type_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='auto_published',
            field=models.BooleanField(default=False),
        ),
    ]
