# Generated by Django 6.0.6 on 2026-08-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_alter_suggestion_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
