# Generated by Django 6.0.6 on 2026-09-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_suggestion_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suggestions/'),
        ),
    ]
