# Generated by Django 6.0.6 on 2026-09-03 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('suggestion_approved', 'اقتراح مقبول'), ('report_resolved', 'بلاغ محلول'), ('distinct_product_scanned', 'منتج مميّز تم مسحه'), ('post_published', 'منشور مجتمعي نُشر'), ('comment_best_answer', 'تعليق اختير كأفضل إجابة'), ('post_reaction_received', 'تفاعل مفيد على منشورك'), ('comment_reaction_received', 'تفاعل مفيد على تعليقك')], max_length=30)),
                ('points', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, default='', max_length=30)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='community_p_user_id_4b62e8_idx')],
                'unique_together': {('user', 'action', 'reference_type', 'reference_id')},
            },
        ),
    ]
