"""
Django settings for basira project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# يحمّل متغيرات من ملف .env المحلي لو موجود (للتطوير فقط — الاستضافة
# تضبط هذي المتغيرات من لوحتها مباشرة، ما تحتاج ملف .env أصلاً)
load_dotenv(BASE_DIR / '.env')


# ── إعدادات الأمان ────────────────────────────────────────────
# كل قيمة هنا تُقرأ من متغير بيئة أولًا، ولو ما وُجد ترجع لنفس القيمة
# القديمة المستخدمة بالتطوير المحلي — يعني المشروع يشتغل بدون أي
# تغيير بتجربتك الحالية، ويصير جاهز للنشر بمجرد ما تحدّد المتغيرات
# على لوحة تحكم الاستضافة (Render/Railway/إلخ).

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-2wfoz*udegoqwje_2bti887)&f=+xx+t464ziw+=&k#ff+6o#$',
)

# DEBUG=False تلقائيًا بالاستضافة (لأنها تضبط DJANGO_DEBUG=False)،
# ويبقى True محليًا كالمعتاد ما لم تحدّد غير ذلك
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# بالاستضافة: حدّد نطاقك الفعلي بمتغير DJANGO_ALLOWED_HOSTS
# (مفصول بفواصل، مثلاً: basira-api.onrender.com,api.basira.app)
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS')
ALLOWED_HOSTS = _allowed_hosts_env.split(',') if _allowed_hosts_env else ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    # مكتبات
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # تطبيقاتنا
    'users',
    'products',
    'entities',
    'categories',
    'articles',
    'suggestions',
    'reports',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # يخدّم ملفات static مباشرة من Django نفسه بدون خادم ويب منفصل —
    # ضروري بالاستضافة (Render وغيرها) لأن DEBUG=False يوقف تقديم static تلقائيًا
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'basira.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

WSGI_APPLICATION = 'basira.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# لو متغير DATABASE_URL موجود (الاستضافة تضبطه تلقائيًا لما تربط قاعدة
# بيانات PostgreSQL)، نستخدمه. وإلا نرجع لإعداداتك المحلية القديمة تمامًا.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ['DATABASE_URL'],
            conn_max_age=600,
            ssl_require=os.environ.get('DJANGO_DB_SSL', 'True') == 'True',
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'basira_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'root'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Africa/Tripoli'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# مجلد يجمع فيه أمر collectstatic كل ملفات static وقت النشر —
# whitenoise يخدّمها من هنا مباشرة
STATIC_ROOT = BASE_DIR / 'staticfiles'

WHITENOISE_MANIFEST_STRICT = False

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

CORS_ALLOW_ALL_ORIGINS = True

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}


AUTH_USER_MODEL = 'users.User'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# ── تخزين دائم للصور عبر Cloudinary (اختياري) ──────────────────
# لو حدّدت متغيرات Cloudinary بيئيًا (بالاستضافة)، كل صور المنتجات/
# الجهات/الاقتراحات تُرفع مباشرة لـ Cloudinary بدل القرص المحلي —
# ضروري لأن أغلب الاستضافات المجانية (Render مثلًا) تمسح أي ملف
# مرفوع محليًا كل ما يُعاد تشغيل الخادم. محليًا (بدون هذي المتغيرات)
# يشتغل بالتخزين المحلي العادي كالمعتاد بدون أي تغيير.
if os.environ.get('CLOUDINARY_CLOUD_NAME'):
    INSTALLED_APPS += ['cloudinary_storage', 'cloudinary']
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    }
    STORAGES['default'] = {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    }


JAZZMIN_SETTINGS = {
    # العنوان
    "site_title": "بصيرة",
    "site_header": "لوحة تحكم بصيرة",
    "site_brand": "بصيرة",
    "welcome_sign": "مرحباً بك في لوحة تحكم بصيرة",
    "copyright": "بصيرة",

    # الأيقونات
    "site_icon": None,
    "site_logo": None,

    # القائمة الجانبية
    "show_sidebar": True,
    "navigation_expanded": True,

    # الروابط السريعة في الأعلى
    "topmenu_links": [
        {"name": "الرئيسية", "url": "admin:index"},
    ],

    # أيقونات القوائم
    "icons": {
        "auth": "fas fa-users-cog",
        "users.user": "fas fa-user",
        "products.product": "fas fa-box",
        "entities.businessentity": "fas fa-building",
        "categories.category": "fas fa-tags",
        "articles.article": "fas fa-newspaper",
        "suggestions.suggestion": "fas fa-lightbulb",
        "reports.report": "fas fa-flag",
    },

    # الثيم
    "theme": "default",
    "dark_mode_theme": None,

    # ترتيب القوائم
    "order_with_respect_to": [
        "products",
        "entities",
        "categories",
        "articles",
        "suggestions",
        "reports",
        "users",
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-success navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
