# Generated by Django 6.0.6 on 2026-08-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_category_report_target_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(blank=True, choices=[('product', 'منتج'), ('entity', 'جهة'), ('community_post', 'منشور مجتمعي')], max_length=20, null=True),
        ),
    ]
