# Generated by Django 6.0.6 on 2026-09-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(blank=True, choices=[('product', 'منتج'), ('entity', 'جهة'), ('community_post', 'منشور مجتمعي'), ('comment', 'تعليق'), ('review', 'تقييم')], max_length=20, null=True),
        ),
    ]
