# Generated by Django 6.0.6 on 2026-08-23 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_reason_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.CharField(max_length=64, unique=True)),
                ('barcode', models.CharField(max_length=100)),
                ('found', models.BooleanField(default=False)),
                ('product_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('status_at_scan', models.CharField(blank=True, default='', max_length=11)),
                ('scanned_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل مسح',
                'verbose_name_plural': 'سجلات المسح',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['user', '-scanned_at'], name='scans_scanh_user_id_bd6e5b_idx')],
            },
        ),
    ]
