# Generated by Django 6.0.6 on 2026-08-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('suggestion_approved', 'اقتراح مقبول'), ('suggestion_rejected', 'اقتراح مرفوض'), ('report_resolved', 'بلاغ محلول'), ('post_published', 'منشور مجتمعي مقبول'), ('post_rejected', 'منشور مجتمعي مرفوض'), ('general', 'عام')], default='general', max_length=30),
        ),
    ]
