# Generated by Django 6.0.6 on 2026-09-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('suggestion_approved', 'اقتراح مقبول'), ('suggestion_rejected', 'اقتراح مرفوض'), ('report_resolved', 'بلاغ محلول'), ('post_published', 'منشور مجتمعي مقبول'), ('post_rejected', 'منشور مجتمعي مرفوض'), ('post_comment', 'تعليق على منشورك'), ('comment_reply', 'رد على تعليقك'), ('general', 'عام')], default='general', max_length=30),
        ),
    ]
