# Generated by Django 6.0.6 on 2026-06-09 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('boycott', 'مقاطعة'), ('caution', 'حذر'), ('good', 'جيد'), ('great', 'رائع')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.category')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entities.businessentity')),
            ],
        ),
    ]
