# Generated by Django 6.0.6 on 2026-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('boycott', 'مقاطعة'), ('caution', 'حذر'), ('alternative', 'بديل')], max_length=11),
        ),
    ]
